name: Config Pages Export
type: module
description: 'Provides utility functionality for exporting and importing config_pages content between environments.'
package: Custom
core_version_requirement: ^9 || ^10
dependencies:
  - drupal:config_pages
