name: Config Pages Export
type: module
description: 'Exports Config Pages entities as configuration, allowing them to be deployed between environments.'
core_version_requirement: ^9 || ^10
package: Configuration
dependencies:
  - drupal:config_pages
